### ISSUE TITLE
elevation values of reactor cores oddly match longitude values- SUSPICIOUS! 

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/geoneutrinos.github.io#15]
Elevation values are very suspicious. Each one I checked in North America and several in South America is the same value as the longitude value. This is an embarrassing problem: It makes the site appear unprofessional.

**Comment by DocOtak** [comment]
This should be fixed by 7253c93. Please verify.

**Comment by stdye** [comment]
Looks better now.
